const ORDER_STATUS = {
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAID: "PAID",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
};

const ROLES = {
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
};

module.exports = {
  ORDER_STATUS,
  ROLES,
};
