ALTER TABLE orders
ADD COLUMN paid_at DATETIME NULL,
ADD COLUMN processed_at DATETIME NULL,
ADD COLUMN shipped_at DATETIME NULL,
ADD COLUMN delivered_at DATETIME NULL,
ADD COLUMN cancelled_at DATETIME NULL;

ALTER TABLE orders
MODIFY COLUMN status ENUM('PAYMENT_PENDING','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED','FAILED','PAYMENT_EXPIRED') NOT NULL DEFAULT 'PAYMENT_PENDING';
