module.exports = {
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PAID: "PAID",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};